FROM 9hitste/appv6:latest

ENV NH_ACCESS_KEY=42948cff9e97420a74d54801a3c73077
ENV NH_SYSTEM_SESSION=yes
ENV NH_HIDE_BROWSER=yes
ENV NH_ALLOW_POPUPS=yes
ENV NH_ALLOW_ADULT=no
ENV NH_ALLOW_CRYPTO=no
ENV NH_CACHE_LIMIT=0
ENV NH_NOTE=railway-9hits
ENV NH_SESSION_NOTE=aliexhelper-traffic

ENTRYPOINT ["/nh.sh"]
CMD ["--access-key=42948cff9e97420a74d54801a3c73077", "--system-session", "--hide-browser=yes", "--allow-crypto=no", "--allow-adult=no", "--cache-limit=0", "--note=railway-9hits", "--session-note=aliexhelper-traffic"]
